### PR TITLE
[venstarthermostat] WIP for submission

### PR DESCRIPTION
**Pull request by digitaldan**
Hi @hww3 its been a little while.  I just spent several hours rebasing our branch against OH master, since we forked so long ago much has changed, and it was not a smooth process.  I opened this PR not for you to merge it into your branch (too many conflicts), but as a place to start a conversation about submitting this to upstream.  I spent a lot of time this weekend updating the code to meet our PR requirements , it now builds and passes code checks in maven.  Take a look at my branch https://github.com/digitaldan/openhab2-addons/commits/venstar-jetty , i was able to keep our commit history  on top of the massive rebase to upstream and this branch will submit cleanly to OH master.   If you are still interested would you like the honors of submitting?  Thanks!

### CODE REVIEW

**Comment by digitaldan** [comment]
Hi, any thoughts?

**Comment by hww3** [comment]
Hi-

I’ve been out of town for a week or so and just got back in. I’ll have a look at this in the next day or two!

Bill

**Comment by digitaldan** [comment]
Great, thanks!

**Comment by digitaldan** [comment]
Ping :-)

**Comment by hww3** [comment]
Hi,

I took some time to look at everything and there remains a problem with the system state field being empty (or “-“ more properly) when using PaperUI and auto-managed things. I believe that’s because the channel configuration in the various xml files describes the channel type as a number type, when the final type is actually a string (due to the value mapping). When PaperUI gets the value “Idle”, etc, and tries to display that as a number, it fails and falls back to the hyphen. 

I fixed the problem unambiguously in my branch by converting the value from the thermostat to a string inside the binding, which makes everything work and avoids the need to know that 1 is heating, etc. The only downside I’ve found is that my grafana charts no longer work, I suspect because my time series data changed from integers to strings.

Bill

**Comment by digitaldan** [comment]
>, when the final type is actually a string (due to the value mapping).

Can you show me where that is happening, the value mapping?   I was looking around to see where that could be, the Thermostat inputs a number and outputs a number, we use DecimalType in the handler, and the XML file exposes it as a Number with no formatting override .  I'm trying to figure out where it would be mapped as a string. This is a shot of my paperUI

image

**Comment by digitaldan** [comment]
One other thought, does adding a state description formatter (`<state pattern="%s" readOnly="true">`)  like this help at all?  You may need to remove and add the thing again for it to take effect.
So for example:
```xml
<channel-type id="systemState">
		<item-type>Number</item-type>
		<label>System State</label>
		<description>Current System Operating State</description>
		<state pattern="%s" readOnly="true">
			<options>
				<option value="0">Idle</option>
				<option value="1">Heating</option>
				<option value="2">Cooling</option>
				<option value="3">Lockout</option>
				<option value="4">Error</option>
			</options>
		</state>
	</channel-type>
```

I notice that the zwave binding does this for all of its thermostats modes and states, their channel definition is nearly identical to this.

**Comment by hww3** [comment]
Hi,

If you take a look in thing-types.xml, you’ll see value mappings for both systemState and systemMode. When the item-type is marked as “Number”, these items will not show the mapped values (Heating, Cooling, etc) unless the item-type is changed to String. Others have reported the same problem, so I’ve ruled out quirkiness in my environment.

Bill

**Comment by digitaldan** [comment]
Gotcha, this sounds like an issue with the paper ui (one of many issues).  Do you want me to change it back?  i doubt the PR reviewers will notice the mismatch in the thing.xml description, but i don't think it's the right solution.  I'm more concerned about getting the PR submitted and keeping this up to date with upstream changes, so i'm ok it thats what you want.

Also I am going to have to move this to our new bnd based build system as all new PR's as of a week or two ago need to be using it. Should not be too bad as I don't think we have any external dependencies.

**Comment by hww3** [comment]
Hi,

I apologize for all of the delays getting back to you; I started a new job last month and my free time hasn’t balanced out yet. I’m hoping to have a bit more time starting in the next few weeks so hopefully I can be helpful again.

It’s possible that there’s a bug in PaperUI (as you point out there are an abundance of them), but I’m almost inclined to think that it’s a poorly explained behavior in the configuration description layer, as I’ve been doing a little investigation into programmatically described configurations and it seems to imply it’s the final output type that’s described. 

Because I’ve had a few other people comment on the behavior, from an end user experience, I think it probably make sense to “make it work” now and then keep an eye on the behavior in case UI bugs get fixed and it breaks down the road.

Bill

**Comment by digitaldan** [comment]
Hi Bill, sorry for the late response as well, I'm actually on holiday for the week.  I will go ahead and change the type back to a string this weekend. (edit to use your name, not mike!)

**Comment by digitaldan** [comment]
Hey Bill, i have made those changes in this branch, do you want to give it a try?  If you are good with the changes, then i will move the binding to the new build system and we can submit it.

**Comment by digitaldan** [comment]
Hi, i just merged in upstream master and also converted the binding to the new build system ( see https://github.com/openhab/openhab2-addons/issues/5005 ) .  Let me know if you are ok with submitting this and I can get the PR review going .

**Comment by hww3** [comment]
Hi,

I’ve been out of town but had a chance to look at all of this and I’m having trouble getting things working in my environment… at least from a PaperUI standpoint.  The system mode and system state items are both set to NULL if I do an items:list, but I haven’t been able to figure out why that is, but I’m still looking into it.

In my branch, I got tired of dealing with the problems and changed the internal representation of the items to a string with values like “idle”, “heat”, etc. That seems more natural, especially if you’re just looking at things without the mapping values, and does an end run around any UI bugs. The downside is that I was exporting things to influxdb and it broke my runtime graphs (but I think that is easily fixed with an updated query).



Bill

**Comment by digitaldan** [comment]
>The system mode and system state items are both set to NULL if I do an items:list,

What version of OH are you running?  Are there any errors when starting the binding up?  

>In my branch, I got tired of dealing with the problems and changed the internal representation of the items to a string with values like “idle”, “heat”, etc

I was hoping we could release as is, since the thermostat  responds to, and reports back as numbers i think this is appropriate for what we are doing and follows what the OH API's were designed for.

**Comment by hww3** [comment]
hi @digitaldan -

It seems that GitHub has been swallowing my email replies to this thread for the last month, hence the lack of communication from me. Sorry for that. Here's an update on the state of things:

OK, so, I spent a few hours over the last week to try to figure out what works and what doesn’t wrt having PaperUI reflect user friendly system mode and state. Here’s what I’ve learned:

1. The combination of factors that results in working varies between 2.3, 2.4 and 2.5. I think the introduction of UoM played a role here.
2. Since I have a version that works for 2.4, I decided to focus on 2.5. I worked directly from a clone of your repo.
3. In order for state mapping to work, the Item type has to be a String and the underlying Type object that the binding uses to update the state has to be a StringType.
4. Having the type as a string is inconvenient for persistence as it isn’t possible to graph system run time without resorting to conversions. 
   - Options for dealing with this include:
        custom query magic on the graphing side of things (up to the user)
        some sort of transformation before the persistence layer grabs the data (up to the user)
        having “hidden” read-only items that are integer values of SystemMode/SystemState that we can graph from (we could add this to the binding and a user could simply opt to use it)

I feel pretty strongly that the default UIs should provide easy to interpret values for all of the fields a binding offers, which Is why I’ve been spending (wasting?) so much effort on this problem. If we have to switch to string value, perhaps we should just make the obvious leap and have the binding map the Venstar integer values for these fields to descriptive strings (like “heat”, “off”, etc)? Then someone who wanted to write rules wouldn’t have to know the underlying Venstar API works. Thoughts?

I switched my own branch to use descriptive strings for both of those items, so I could incorporate that, plus make the changes I described in the last option pretty quickly, if you think that’s a reasonable approach. I’m not sure if the gate for 2.5 has closed yet, but I can set aside some time over the next few days to get this merged and get value mapping squared away.

**Comment by digitaldan** [comment]
So i thought i replied to this a few weeks ago, but apparently I never clicked the "comment" button! Apologies!  
I agree the paperUI should do the right thing,  and would prefer to keep the native values for state and mode, but I can live with with String if you prefer it :-) Its probably not a big deal.   FYI we are very close to having a paperui replacement , see Yannicks updates, like this one https://twitter.com/yschaus/status/1140709636766670848 .  I'll checkout you branch and look.

I'm not sure if 2.5 has closed, I just submitted a new binding last week, 50/50 it gets in.  We should probably start making changes based on my branch since its has all the build changes along with various other fixes needed  for submission.

**Comment by digitaldan** [comment]
FYi, i looked at your branch, LGTM regarding the mode and state changes to strings. 👍

**Comment by hww3** [comment]
Cool. I'll work on getting this integrated, along with a fix for supporting thermostats where v4 is the latest firmware. Seems the discovery response changed between v4 and v5. Wondering if maybe the solution to the Paper UI problem is to keep the number typed items and add string typed items that will eventually go away when the mapping works better with a future ui? That way, you're happy, and my time series data is happy, and Paper UI can be made happy with a little effort. Sound reasonable?

**Comment by digitaldan** [comment]
>Wondering if maybe the solution to the Paper UI problem is to keep the number typed items and add string typed items that will eventually go away when the mapping works better with a future ui? That way, you're happy, and my time series data is happy, and Paper UI can be made happy with a little effort. Sound reasonable?

Sounds good, maybe we call the Integer value something like systemModeRaw and systemStateRaw , mark them both as advanced channels,  and then use your Enum/String value as the default one.   I was reading up on the ESH internal docs, and i don't think String label matching actually is supported on number values.

**Comment by hww3** [comment]
OK, I think I've got my additions for the raw channels added atop your  branch... seemed like that was the easier merge approach. I'm going to test it (requiring an update to 2.5M) and should have this squared away this weekend. Thanks again for all of your patience in this process!

**Comment by digitaldan** [comment]
Sounds good!

**Comment by hww3** [comment]
merged... I think (and hopefully not completely messed up in the process)!

**Comment by digitaldan** [comment]
Awesome!

**Pull request merged**
