### PR TITLE
Venstar jetty

### PR DESCRIPTION
**Pull request by digitaldan**
Hi, sorry this is so huge! i have been tweaking this in my free time, which has been few and far between for the last few weeks, and thought it would be a good point to share and get feedback. Couple things about this PR:

Removes all Apache dependencies for Jetty,
Temporary adds jetty libs, we can removes this when ESH/OH upgrades to jetty 9.4
Simplifies and reduces the handler code
Simplifies and reduces the discovery code

Big commits like this are hard to see from diffs, might be best to load it in your IDE and check it out. There's still a bunch of work to do around cleaning up comments, lint issues and null checks, but so far this is in pretty good shape I think.

### CODE REVIEW

**Comment by hww3** [comment]
Thanks, @digitaldan... I had a quick look at the changes and will try to make some time this weekend to give it some testing.

**Comment by hww3** [comment]
So, I've had a look at the changes and I've noticed one or two things... please pardon the length of the comment as I think out loud...

I have this PR included in a test binding I've got installed locally. I noticed that I wasn't able to delete an existing thermostat using PaperUI, as I was getting a "unable to delete an unmanaged thing". I think that must be a bug in the OpenHAB platform, right? I manually edited my JSONDB so that I could get the binding to re-add it.

1. The discovery process only runs when manually triggered. 

I feel like that's a "regression" for 2 reasons: first, I think if we've got the ability to do discovery, it seems like the most user friendly thing would be to do that automatically. Also, running the discovery process is needed to pick up changes to devices, such as IP addresses. I tested this by renumbering my thermostats and they went offline until I ran a manual discovery on them.

2. I have some misgivings about making the URL configurable... the thermostat says what it's url should be in discovery messages and it seems like a potential source of confusion to have it be modifiable only to have the discovery process change it.

I suppose if you wanted to manage thermostats that were beyond the discovery domain (i.e., on a different IP subnet), then this would be the way to do it. Is that what you were thinking as far as a use case? Discovery uses SSDP; is there a standard approach for proxying across subnets (such as there is for DHCP and other protocols)? It seems like if there were, that would be a preferable approach. If not, I guess that makes sense, though we'll want to include a prominent note in documentation that indicates that you shouldn't ordinarily need to specify this outside of that scenario. 

Also, as a side note, I'll add a ticket to add support for the new system of units mechanism. I'd also like to see if it makes sense to harmonize the state/mode values so that they work more seamlessly with e.g. the HomeKit add-on.

**Comment by digitaldan** [comment]
>I noticed that I wasn't able to delete an existing thermostat using PaperUI,

This is probably a bug, i'll take a look at it, its possible I changed something which made things added in earlier versions of the binding not get removed properly (the system does call the binding on such events)

>The discovery process only runs when manually triggered.

This is just a misconfiguration on my part, I noticed it too and just forgot to come back to it, I'll make sure its enable as it should auto discover. 

 >I have some misgivings about making the URL configurable

So we need to provide a way for users to configure things manually through configuration files, not all users use the paperui to add and manage things.  So either we have the URL as a config or the MAC (uuid) address ( and not just part of the thing identifier) .  It is becoming quite common to have "things" on a separate network as you mentioned above.   There is a growing distrust of all the internet connected dishwashers, tv's and such.  So auto discovery is not always possible across subnets ( i ran into this with the squeezebox binding and a few users). 

I do like auto updating the URL if it would work reliably, its a more elegant solution.  So I would be ok for changing the URL back to auto discovery and adding the MAC as a required config which should work for non paperui configs, and still make auto discovery setups work too.   If we run into users who cannot make this work, we can later add back in the ability to manually manually configure the host as an optional property. 
 
>Also, as a side note, I'll add a ticket to add support for the new system of units mechanism. 

That would be awesome!

> I'd also like to see if it makes sense to harmonize the state/mode values so that they work more seamlessly with e.g. the HomeKit add-on.

I would not "map" the values the thermostat requires to match the homekit binding (or any other binding),  the way they are defined in the thing file is exactly how ESH was designed to work with mapping thing specific values to items.  Also, the current values are almost identical to Z-Wave values which represents a lot of thermostats.

**Comment by digitaldan** [comment]
>So we need to provide a way for users to configure things manually through configuration files, not all users use the paperui to add and manage things. 

I take this back, after thinking about this, I'm also ok with making the UUID/Mac required in the thing name/thingUid and not actually a part of the config.  So the way you had it was fine, I'll change it back.

**Comment by hww3** [comment]
You can definitely count me as someone who is paranoid about security... I have all of my IOT/smarthome devices on an isolated network. My openhab node has an interface on the IOT network and another on my home network. I did have to spend a fair amount of effort to get discovery to work on multiple interfaces, so I wouldn't be surprised if that didn't generally work in other bindings.

**Comment by hww3** [comment]
> I would not "map" the values the thermostat requires to match the homekit binding (or any other binding), the way they are defined in the thing file is exactly how ESH was designed to work with mapping thing specific values to items. Also, the current values are almost identical to Z-Wave values which represents a lot of thermostats.

Ok, I tried to figure out if there was a common vocabulary but wasn't completely successful. The solution to my difficulties may lie on the HomeKit binding end of things. Will investigate further.

> Also, as a side note, I'll add a ticket to add support for the new system of units mechanism.
That would be awesome!

I'm out of town for the next week or so but will look into the changes required for that when I return.

**Pull request merged**
